# Generated by Django 3.1.1 on 2021-01-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zombie',
            old_name='cuteness_level',
            new_name='rot_level',
        ),
    ]
